### PR TITLE
Conditionally compile call to gvToolTred on Windows

### PR DESCRIPTION
**Pull request by mattt**
Related to #21

### CODE REVIEW

**Comment by mattt** [comment]
@compnerd Is this sufficient for your purposes? Or would I need to do something more drastic, like this?

```c
#ifndef _WIN32
extern int gvToolTred(graph_t *g);
#endif
```

**Comment by compnerd** [comment]
No, I'm afraid that wont be sufficient.  I can push something that should be.

**Comment by compnerd** [comment]
I think that should be sufficient.  The declaration isn't particularly important.

**Comment by compnerd** [comment]
Verified that this actually allows the build to continue.  Until the upstream MR is merged, I'm going to go ahead and merge this change for now.  Once we have a tag with this change, I think that we can actually shift the focus to swift-doc itself and things above it.

**Pull request merged**
